name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *' # Monthly
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@0.5.0

  build:
    runs-on: ubuntu-latest
    needs: [shellcheck]
    steps:
      - uses: actions/checkout@v2
      - name: Clone Vim
        run: |
          git clone --bare https://github.com/vim/vim.git
      - name: Build help tag version list
        run: |
          ./difftags ./vim.git > tag-versions
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          path: tag-versions

      - name: Build frontend
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
